name: reviewdog
on: [push]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          reporter: github-check
          files: content  # path to lint
          fail_on_error: true
          level: warning
          debug: true
          config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini