name: reviewdog
on: [pull_request]

jobs:
  vale-lint:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{ join(github.event.pull_request.changed_files, ' ') }}
          reporter: github-check
          fail_on_error: true